workflows:
  android-free:
    name: Android Free Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.32.2
      java: 17
      vars:
        # Enhanced build time optimization variables
        GRADLE_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2"
        XCODE_PARALLEL_JOBS: "6"

        # Build acceleration variables
        GRADLE_DAEMON: "true"
        GRADLE_PARALLEL: "true"
        GRADLE_CACHING: "true"
        FLUTTER_PUB_CACHE: "true"
        ENABLE_GRADLE_DAEMON: "true"
        GRADLE_OPTS_DAEMON: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true"

        # Asset optimization
        ASSET_OPTIMIZATION: "true"
        IMAGE_COMPRESSION: "true"
        PARALLEL_DOWNLOADS: "true"

        APP_ID: $APP_ID
        WORKFLOW_ID: "android-free"
        BRANCH: $BRANCH
        VERSION_NAME: $VERSION_NAME
        VERSION_CODE: $VERSION_CODE
        APP_NAME: $APP_NAME
        ORG_NAME: $ORG_NAME
        WEB_URL: $WEB_URL
        PKG_NAME: $PKG_NAME
        EMAIL_ID: $EMAIL_ID
        USER_NAME: $USER_NAME
        PUSH_NOTIFY: "false"
        IS_CHATBOT: $IS_CHATBOT
        IS_DOMAIN_URL: "false"
        IS_SPLASH: $IS_SPLASH
        IS_PULLDOWN: $IS_PULLDOWN
        IS_BOTTOMMENU: $IS_BOTTOMMENU
        IS_LOAD_IND: $IS_LOAD_IND
        IS_CAMERA: $IS_CAMERA
        IS_LOCATION: $IS_LOCATION
        IS_MIC: $IS_MIC
        IS_NOTIFICATION: $IS_NOTIFICATION
        IS_CONTACT: $IS_CONTACT
        IS_BIOMETRIC: $IS_BIOMETRIC
        IS_CALENDAR: $IS_CALENDAR
        IS_STORAGE: $IS_STORAGE
        LOGO_URL: $LOGO_URL
        SPLASH_URL: $SPLASH_URL
        SPLASH_BG_URL: $SPLASH_BG_URL
        SPLASH_BG_COLOR: $SPLASH_BG_COLOR
        SPLASH_TAGLINE: $SPLASH_TAGLINE
        SPLASH_TAGLINE_COLOR: $SPLASH_TAGLINE_COLOR
        SPLASH_ANIMATION: $SPLASH_ANIMATION
        SPLASH_DURATION: $SPLASH_DURATION
        #        KEY_STORE_URL: ""
        ENABLE_EMAIL_NOTIFICATIONS: "true"
        EMAIL_SMTP_SERVER: "smtp.gmail.com"
        EMAIL_SMTP_PORT: "587"
        EMAIL_SMTP_USER: "prasannasrie@gmail.com"
        EMAIL_SMTP_PASS: "lrnu krfm aarp urux"
    scripts:
      - name: Build Android APK
        script: |
          chmod +x lib/scripts/android/*.sh
          chmod +x lib/scripts/utils/*.sh
          ./lib/scripts/android/main.sh
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - output/android/app-release.apk

  android-paid:
    name: Android Paid Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.32.2
      java: 17
      vars:
        # Enhanced build time optimization variables
        GRADLE_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2"
        XCODE_PARALLEL_JOBS: "6"

        # Build acceleration variables
        GRADLE_DAEMON: "true"
        GRADLE_PARALLEL: "true"
        GRADLE_CACHING: "true"
        FLUTTER_PUB_CACHE: "true"
        ENABLE_GRADLE_DAEMON: "true"
        GRADLE_OPTS_DAEMON: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true"

        # Asset optimization
        ASSET_OPTIMIZATION: "true"
        IMAGE_COMPRESSION: "true"
        PARALLEL_DOWNLOADS: "true"

        APP_ID: $APP_ID
        WORKFLOW_ID: "android-paid"
        BRANCH: $BRANCH
        VERSION_NAME: $VERSION_NAME
        VERSION_CODE: $VERSION_CODE
        APP_NAME: $APP_NAME
        ORG_NAME: $ORG_NAME
        WEB_URL: $WEB_URL
        PKG_NAME: $PKG_NAME
        EMAIL_ID: $EMAIL_ID
        USER_NAME: $USER_NAME
        PUSH_NOTIFY: $PUSH_NOTIFY
        IS_CHATBOT: $IS_CHATBOT
        IS_DOMAIN_URL: $IS_DOMAIN_URL
        IS_SPLASH: $IS_SPLASH
        IS_PULLDOWN: $IS_PULLDOWN
        IS_BOTTOMMENU: $IS_BOTTOMMENU
        IS_LOAD_IND: $IS_LOAD_IND
        IS_CAMERA: $IS_CAMERA
        IS_LOCATION: $IS_LOCATION
        IS_MIC: $IS_MIC
        IS_NOTIFICATION: $IS_NOTIFICATION
        IS_CONTACT: $IS_CONTACT
        IS_BIOMETRIC: $IS_BIOMETRIC
        IS_CALENDAR: $IS_CALENDAR
        IS_STORAGE: $IS_STORAGE
        LOGO_URL: $LOGO_URL
        SPLASH_URL: $SPLASH_URL
        SPLASH_BG_URL: $SPLASH_BG_URL
        SPLASH_BG_COLOR: $SPLASH_BG_COLOR
        SPLASH_TAGLINE: $SPLASH_TAGLINE
        SPLASH_TAGLINE_COLOR: $SPLASH_TAGLINE_COLOR
        SPLASH_ANIMATION: $SPLASH_ANIMATION
        SPLASH_DURATION: $SPLASH_DURATION
        FIREBASE_CONFIG_ANDROID: $FIREBASE_CONFIG_ANDROID
        #        KEY_STORE_URL: ""
        ENABLE_EMAIL_NOTIFICATIONS: "true"
        EMAIL_SMTP_SERVER: "smtp.gmail.com"
        EMAIL_SMTP_PORT: "587"
        EMAIL_SMTP_USER: "prasannasrie@gmail.com"
        EMAIL_SMTP_PASS: "lrnu krfm aarp urux"
    scripts:
      - name: Build Android APK
        script: |
          chmod +x lib/scripts/android/*.sh
          chmod +x lib/scripts/utils/*.sh
          ./lib/scripts/android/main.sh
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - output/android/app-release.apk

  android-publish:
    name: Android Publish Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.32.2
      java: 17
      vars:
        # Enhanced build time optimization variables
        GRADLE_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2"
        XCODE_PARALLEL_JOBS: "6"

        # Build acceleration variables
        GRADLE_DAEMON: "true"
        GRADLE_PARALLEL: "true"
        GRADLE_CACHING: "true"
        FLUTTER_PUB_CACHE: "true"
        ENABLE_GRADLE_DAEMON: "true"
        GRADLE_OPTS_DAEMON: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true"

        # Asset optimization
        ASSET_OPTIMIZATION: "true"
        IMAGE_COMPRESSION: "true"
        PARALLEL_DOWNLOADS: "true"

        APP_ID: $APP_ID
        WORKFLOW_ID: "android-publish"
        BRANCH: $BRANCH
        VERSION_NAME: $VERSION_NAME
        VERSION_CODE: $VERSION_CODE
        APP_NAME: $APP_NAME
        ORG_NAME: $ORG_NAME
        WEB_URL: $WEB_URL
        PKG_NAME: $PKG_NAME
        EMAIL_ID: $EMAIL_ID
        USER_NAME: $USER_NAME
        PUSH_NOTIFY: $PUSH_NOTIFY
        IS_CHATBOT: $IS_CHATBOT
        IS_DOMAIN_URL: $IS_DOMAIN_URL
        IS_SPLASH: $IS_SPLASH
        IS_PULLDOWN: $IS_PULLDOWN
        IS_BOTTOMMENU: $IS_BOTTOMMENU
        IS_LOAD_IND: $IS_LOAD_IND
        IS_CAMERA: $IS_CAMERA
        IS_LOCATION: $IS_LOCATION
        IS_MIC: $IS_MIC
        IS_NOTIFICATION: $IS_NOTIFICATION
        IS_CONTACT: $IS_CONTACT
        IS_BIOMETRIC: $IS_BIOMETRIC
        IS_CALENDAR: $IS_CALENDAR
        IS_STORAGE: $IS_STORAGE
        LOGO_URL: $LOGO_URL
        SPLASH_URL: $SPLASH_URL
        SPLASH_BG_URL: $SPLASH_BG_URL
        SPLASH_BG_COLOR: $SPLASH_BG_COLOR
        SPLASH_TAGLINE: $SPLASH_TAGLINE
        SPLASH_TAGLINE_COLOR: $SPLASH_TAGLINE_COLOR
        SPLASH_ANIMATION: $SPLASH_ANIMATION
        SPLASH_DURATION: $SPLASH_DURATION
        FIREBASE_CONFIG_ANDROID: $FIREBASE_CONFIG_ANDROID
        KEY_STORE_URL: $KEY_STORE_URL
        CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        CM_KEY_ALIAS: $CM_KEY_ALIAS
        CM_KEY_PASSWORD: $CM_KEY_PASSWORD
        ENABLE_EMAIL_NOTIFICATIONS: "true"
        EMAIL_SMTP_SERVER: "smtp.gmail.com"
        EMAIL_SMTP_PORT: "587"
        EMAIL_SMTP_USER: "prasannasrie@gmail.com"
        EMAIL_SMTP_PASS: "lrnu krfm aarp urux"
    scripts:
      - name: Build Android APK and AAB
        script: |
          chmod +x lib/scripts/android/*.sh
          chmod +x lib/scripts/utils/*.sh
          ./lib/scripts/android/main.sh
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - output/android/app-release.apk
      - output/android/app-release.aab

  ios-appstore:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.32.2
      java: 17
      xcode: 15.4
      cocoapods: 1.16.2
      vars:
        # Enhanced build time optimization variables
        GRADLE_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2"
        XCODE_PARALLEL_JOBS: "6"

        # iOS build acceleration
        XCODE_FAST_BUILD: "true"
        COCOAPODS_FAST_INSTALL: "true"
        XCODE_SKIP_SIGNING: "false"
        XCODE_OPTIMIZATION: "true"

        # Asset optimization
        ASSET_OPTIMIZATION: "true"
        IMAGE_COMPRESSION: "true"
        PARALLEL_DOWNLOADS: "true"

        APP_ID: $APP_ID
        WORKFLOW_ID: "ios-appstore"
        BRANCH: $BRANCH
        VERSION_NAME: $VERSION_NAME
        VERSION_CODE: $VERSION_CODE
        APP_NAME: $APP_NAME
        ORG_NAME: $ORG_NAME
        WEB_URL: $WEB_URL
        BUNDLE_ID: $BUNDLE_ID
        EMAIL_ID: $EMAIL_ID
        USER_NAME: $USER_NAME
        PUSH_NOTIFY: $PUSH_NOTIFY
        IS_CHATBOT: $IS_CHATBOT
        IS_DOMAIN_URL: $IS_DOMAIN_URL
        IS_SPLASH: $IS_SPLASH
        IS_PULLDOWN: $IS_PULLDOWN
        IS_BOTTOMMENU: $IS_BOTTOMMENU
        IS_LOAD_IND: $IS_LOAD_IND
        IS_CAMERA: $IS_CAMERA
        IS_LOCATION: $IS_LOCATION
        IS_MIC: $IS_MIC
        IS_NOTIFICATION: $IS_NOTIFICATION
        IS_CONTACT: $IS_CONTACT
        IS_BIOMETRIC: $IS_BIOMETRIC
        IS_CALENDAR: $IS_CALENDAR
        IS_STORAGE: $IS_STORAGE
        LOGO_URL: $LOGO_URL
        SPLASH_URL: $SPLASH_URL
        SPLASH_BG_URL: $SPLASH_BG_URL
        SPLASH_BG_COLOR: $SPLASH_BG_COLOR
        SPLASH_TAGLINE: $SPLASH_TAGLINE
        SPLASH_TAGLINE_COLOR: $SPLASH_TAGLINE_COLOR
        SPLASH_ANIMATION: $SPLASH_ANIMATION
        SPLASH_DURATION: $SPLASH_DURATION
        FIREBASE_CONFIG_IOS: $FIREBASE_CONFIG_IOS
        APPLE_TEAM_ID: $APPLE_TEAM_ID
        APNS_KEY_ID: $APNS_KEY_ID
        APNS_AUTH_KEY_URL: $APNS_AUTH_KEY_URL
        CERT_PASSWORD: $CERT_PASSWORD
        PROFILE_URL: $PROFILE_URL
        CERT_P12_URL: $CERT_P12_URL
        CERT_CER_URL: $CERT_CER_URL
        CERT_KEY_URL: $CERT_KEY_URL
        PROFILE_TYPE: "app-store"
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        ENABLE_EMAIL_NOTIFICATIONS: "true"
        EMAIL_SMTP_SERVER: "smtp.gmail.com"
        EMAIL_SMTP_PORT: "587"
        EMAIL_SMTP_USER: "prasannasrie@gmail.com"
        EMAIL_SMTP_PASS: "lrnu krfm aarp urux"
        ENABLE_DEVICE_SPECIFIC_BUILDS: $ENABLE_DEVICE_SPECIFIC_BUILDS
        INSTALL_URL: $INSTALL_URL
        DISPLAY_IMAGE_URL: $DISPLAY_IMAGE_URL
        FULL_SIZE_IMAGE_URL: $FULL_SIZE_IMAGE_URL
        THINNING: $THINNING
    scripts:
      - name: Build iOS App Store IPA
        script: |
          chmod +x lib/scripts/ios/*.sh
          chmod +x lib/scripts/utils/*.sh
          ./lib/scripts/ios/main.sh
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/ios/ipa/*.ipa
      - output/ios/Runner.ipa

  ios-adhoc:
    name: iOS Ad Hoc Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.32.2
      java: 17
      xcode: 15.4
      cocoapods: 1.16.2
      vars:
        # Enhanced build time optimization variables
        GRADLE_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2"
        XCODE_PARALLEL_JOBS: "6"

        # iOS build acceleration
        XCODE_FAST_BUILD: "true"
        COCOAPODS_FAST_INSTALL: "true"
        XCODE_SKIP_SIGNING: "false"
        XCODE_OPTIMIZATION: "true"

        # Asset optimization
        ASSET_OPTIMIZATION: "true"
        IMAGE_COMPRESSION: "true"
        PARALLEL_DOWNLOADS: "true"

        APP_ID: $APP_ID
        WORKFLOW_ID: "ios-adhoc"
        BRANCH: $BRANCH
        VERSION_NAME: $VERSION_NAME
        VERSION_CODE: $VERSION_CODE
        APP_NAME: $APP_NAME
        ORG_NAME: $ORG_NAME
        WEB_URL: $WEB_URL
        BUNDLE_ID: $BUNDLE_ID
        EMAIL_ID: $EMAIL_ID
        USER_NAME: $USER_NAME
        PUSH_NOTIFY: $PUSH_NOTIFY
        IS_CHATBOT: $IS_CHATBOT
        IS_DOMAIN_URL: $IS_DOMAIN_URL
        IS_SPLASH: $IS_SPLASH
        IS_PULLDOWN: $IS_PULLDOWN
        IS_BOTTOMMENU: $IS_BOTTOMMENU
        IS_LOAD_IND: $IS_LOAD_IND
        IS_CAMERA: $IS_CAMERA
        IS_LOCATION: $IS_LOCATION
        IS_MIC: $IS_MIC
        IS_NOTIFICATION: $IS_NOTIFICATION
        IS_CONTACT: $IS_CONTACT
        IS_BIOMETRIC: $IS_BIOMETRIC
        IS_CALENDAR: $IS_CALENDAR
        IS_STORAGE: $IS_STORAGE
        LOGO_URL: $LOGO_URL
        SPLASH_URL: $SPLASH_URL
        SPLASH_BG_URL: $SPLASH_BG_URL
        SPLASH_BG_COLOR: $SPLASH_BG_COLOR
        SPLASH_TAGLINE: $SPLASH_TAGLINE
        SPLASH_TAGLINE_COLOR: $SPLASH_TAGLINE_COLOR
        SPLASH_ANIMATION: $SPLASH_ANIMATION
        SPLASH_DURATION: $SPLASH_DURATION
        FIREBASE_CONFIG_IOS: $FIREBASE_CONFIG_IOS
        APPLE_TEAM_ID: $APPLE_TEAM_ID
        APNS_KEY_ID: $APNS_KEY_ID
        APNS_AUTH_KEY_URL: $APNS_AUTH_KEY_URL
        CERT_PASSWORD: $CERT_PASSWORD
        PROFILE_URL: $PROFILE_URL
        CERT_P12_URL: $CERT_P12_URL
        CERT_CER_URL: $CERT_CER_URL
        CERT_KEY_URL: $CERT_KEY_URL
        PROFILE_TYPE: "ad-hoc"
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        ENABLE_EMAIL_NOTIFICATIONS: "true"
        EMAIL_SMTP_SERVER: "smtp.gmail.com"
        EMAIL_SMTP_PORT: "587"
        EMAIL_SMTP_USER: "prasannasrie@gmail.com"
        EMAIL_SMTP_PASS: "lrnu krfm aarp urux"
        ENABLE_DEVICE_SPECIFIC_BUILDS: $ENABLE_DEVICE_SPECIFIC_BUILDS
        INSTALL_URL: $INSTALL_URL
        DISPLAY_IMAGE_URL: $DISPLAY_IMAGE_URL
        FULL_SIZE_IMAGE_URL: $FULL_SIZE_IMAGE_URL
        THINNING: $THINNING
    scripts:
      - name: Build iOS Ad Hoc IPA
        script: |
          chmod +x lib/scripts/ios/*.sh
          chmod +x lib/scripts/utils/*.sh
          ./lib/scripts/ios/main.sh
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/ios/ipa/*.ipa
      - output/ios/Runner.ipa

  combined:
    name: Universal Combined Build (Android + iOS)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.32.2
      java: 17
      xcode: 15.4
      cocoapods: 1.16.2
      vars:
        # Enhanced build time optimization variables
        GRADLE_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G -XX:ReservedCodeCacheSize=1G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseParallelGC -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2"
        XCODE_PARALLEL_JOBS: "6"

        # Build acceleration variables
        GRADLE_DAEMON: "true"
        GRADLE_PARALLEL: "true"
        GRADLE_CACHING: "true"
        FLUTTER_PUB_CACHE: "true"
        ENABLE_GRADLE_DAEMON: "true"
        GRADLE_OPTS_DAEMON: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true"

        # iOS build acceleration
        XCODE_FAST_BUILD: "true"
        COCOAPODS_FAST_INSTALL: "true"
        XCODE_SKIP_SIGNING: "false"
        XCODE_OPTIMIZATION: "true"

        # Asset optimization
        ASSET_OPTIMIZATION: "true"
        IMAGE_COMPRESSION: "true"
        PARALLEL_DOWNLOADS: "true"

        # Universal App Configuration
        APP_ID: $APP_ID
        WORKFLOW_ID: "combined"
        BRANCH: $BRANCH
        VERSION_NAME: $VERSION_NAME
        VERSION_CODE: $VERSION_CODE
        APP_NAME: $APP_NAME
        ORG_NAME: $ORG_NAME
        WEB_URL: $WEB_URL
        PKG_NAME: $PKG_NAME
        BUNDLE_ID: $BUNDLE_ID
        EMAIL_ID: $EMAIL_ID
        USER_NAME: $USER_NAME

        # Feature Flags (Auto-detected)
        PUSH_NOTIFY: $PUSH_NOTIFY
        IS_CHATBOT: $IS_CHATBOT
        IS_DOMAIN_URL: $IS_DOMAIN_URL
        IS_SPLASH: $IS_SPLASH
        IS_PULLDOWN: $IS_PULLDOWN
        IS_BOTTOMMENU: $IS_BOTTOMMENU
        IS_LOAD_IND: $IS_LOAD_IND
        IS_CAMERA: $IS_CAMERA
        IS_LOCATION: $IS_LOCATION
        IS_MIC: $IS_MIC
        IS_NOTIFICATION: $IS_NOTIFICATION
        IS_CONTACT: $IS_CONTACT
        IS_BIOMETRIC: $IS_BIOMETRIC
        IS_CALENDAR: $IS_CALENDAR
        IS_STORAGE: $IS_STORAGE

        # UI/Branding Configuration
        LOGO_URL: $LOGO_URL
        SPLASH_URL: $SPLASH_URL
        SPLASH_BG_URL: $SPLASH_BG_URL
        SPLASH_BG_COLOR: $SPLASH_BG_COLOR
        SPLASH_TAGLINE: $SPLASH_TAGLINE
        SPLASH_TAGLINE_COLOR: $SPLASH_TAGLINE_COLOR
        SPLASH_ANIMATION: $SPLASH_ANIMATION
        SPLASH_DURATION: $SPLASH_DURATION

        # Android Configuration (Auto-detected)
        FIREBASE_CONFIG_ANDROID: $FIREBASE_CONFIG_ANDROID
        KEY_STORE_URL: $KEY_STORE_URL
        CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        CM_KEY_ALIAS: $CM_KEY_ALIAS
        CM_KEY_PASSWORD: $CM_KEY_PASSWORD

        # iOS Configuration (Auto-detected)
        FIREBASE_CONFIG_IOS: $FIREBASE_CONFIG_IOS
        APPLE_TEAM_ID: $APPLE_TEAM_ID
        APNS_KEY_ID: $APNS_KEY_ID
        APNS_AUTH_KEY_URL: $APNS_AUTH_KEY_URL
        CERT_PASSWORD: $CERT_PASSWORD
        PROFILE_URL: $PROFILE_URL
        CERT_P12_URL: $CERT_P12_URL
        CERT_CER_URL: $CERT_CER_URL
        CERT_KEY_URL: $CERT_KEY_URL
        PROFILE_TYPE: $PROFILE_TYPE
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER

        # Email Configuration
        ENABLE_EMAIL_NOTIFICATIONS: "true"
        EMAIL_SMTP_SERVER: "smtp.gmail.com"
        EMAIL_SMTP_PORT: "587"
        EMAIL_SMTP_USER: "prasannasrie@gmail.com"
        EMAIL_SMTP_PASS: "lrnu krfm aarp urux"

        # iOS Distribution Options
        ENABLE_DEVICE_SPECIFIC_BUILDS: $ENABLE_DEVICE_SPECIFIC_BUILDS
        INSTALL_URL: $INSTALL_URL
        DISPLAY_IMAGE_URL: $DISPLAY_IMAGE_URL
        FULL_SIZE_IMAGE_URL: $FULL_SIZE_IMAGE_URL
        THINNING: $THINNING

    scripts:
      - name: Universal Combined Build
        script: |
          chmod +x lib/scripts/combined/*.sh
          chmod +x lib/scripts/utils/*.sh
          ./lib/scripts/combined/main.sh
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa
      - ios/build/ios/ipa/*.ipa
      - output/android/app-release.apk
      - output/android/app-release.aab
      - output/ios/Runner.ipa
